/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ec566a5fb57312a371cf491821bf0b19)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "UserSession";
	}
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
		SESSION_SECRET: string;
		AUTH_SECRET_KEY: string;
		USER_SESSION_DO: DurableObjectNamespace<import("./src/worker").UserSession>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET" | "AUTH_SECRET_KEY">> {}
}
