/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: a4b27ae1fe88bf283e38eb477b0f472d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "UserSession";
	}
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
		USER_SESSION_DO: DurableObjectNamespace<import("./src/worker").UserSession>;
	}
}
interface Env extends Cloudflare.Env {}
