/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 666c085c947a85eb5480b4e53d6851c4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "UserSession" | "CoachAgent";
	}
	interface Env {
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		SESSION_SECRET: string;
		AUTH_SECRET_KEY: string;
		OPENAI_API_KEY: string;
		USER_SESSION_DO: DurableObjectNamespace<import("./src/worker").UserSession>;
		CoachAgent: DurableObjectNamespace<import("./src/worker").CoachAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET" | "AUTH_SECRET_KEY" | "OPENAI_API_KEY">> {}
}
